In [12]:
import numpy as  np 
arr1 = np.array([[1, 2, 3,4, 5, 6]])
print('1d array', arr1)
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print('2d array',arr2)
arr3 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("3D array:", arr3)

1d array [[1 2 3 4 5 6]]
2d array [[ 7  8  9]
 [10 11 12]]
3D array: [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
zeros_arr = np.zeros((1, 2))
print("Zeros array:", zeros_arr)

# Array of ones
ones_arr = np.ones((3, 2))
print("Ones array:\n", ones_arr)

# Array filled with a constant value
full_arr = np.full((2, 3), 9)
print("Full array:\n", full_arr)

# Identity matrix
identity_arr = np.eye(9)
print("Identity matrix:\n", identity_arr)

Zeros array: [[0. 0.]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full array:
 [[9 9 9]
 [9 9 9]]
Identity matrix:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [21]:
range_arr = np.arange(0, 20, 2)   # start, stop, step
print("arange array:", range_arr)

# linspace 
lin_arr = np.linspace(0, 1, 2)    
print("linspace array:", lin_arr)

# Random arrays
rand_arr = np.random.rand(2, 3)     
randint_arr = np.random.randint(1, 100, size=(2, 3)) 
print("Random float array:", rand_arr)
print("Random integer array:", randint_arr)

arange array: [ 0  2  4  6  8 10 12 14 16 18]
linspace array: [0. 1.]
Random float array: [[0.42084762 0.78371462 0.67212277]
 [0.28607127 0.69007638 0.21052006]]
Random integer array: [[69 98 92]
 [27 73 40]]


In [26]:
exercise1_a = np.zeros((4, 4))
exercise1_b = np.arange(1, 61, 2)
print(exercise1_a)
print(exercise1_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59]


In [ ]:
sample = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", sample)
print("Shape:", sample.shape)      
print("Dimensions:", sample.ndim)  
print("Size:", sample.size)        
print("Data type:", sample.dtype)  

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


In [29]:
reshaped = sample.reshape(3, 2)   
print("Reshaped (3x2):\n", reshaped)


flat = sample.flatten()
print("Flattened:", flat)


print("Transpose:\n", sample.T)

Reshaped (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Flattened: [1 2 3 4 5 6]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
a = np.array([11, 12, 13])
b = np.array([14, 15, 16])

joined = np.concatenate((a, b))
print("Concatenated:", joined)

stacked_v = np.vstack((a, b))   
stacked_h = np.hstack((a, b))   
print("Vertical stack:\n", stacked_v)
print("Horizontal stack:", stacked_h)

Concatenated: [11 12 13 14 15 16]
Vertical stack:
 [[11 12 13]
 [14 15 16]]
Horizontal stack: [11 12 13 14 15 16]


In [38]:
unsort = np.array([25, 2, 19, 61, 0])
sort_arr = np.sort(unsort)
print("Original:", unsort)
print("Sort:", sort_arr)

Original: [25  2 19 61  0]
Sort: [ 0  2 19 25 61]


In [39]:
ex2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", ex2.shape)
print("Size:", ex2.size)
print("Reshaped:\n", ex2.reshape(3, 2))

Shape: (2, 3)
Size: 6
Reshaped:
 [[1 2]
 [3 4]
 [5 6]]


In [43]:
x = np.array([10, 20, 30, 40,50])
y = np.array([11, 22, 33, 44,55])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)
print("Power:", x ** 2)

Addition: [ 21  42  63  84 105]
Subtraction: [-1 -2 -3 -4 -5]
Multiplication: [ 110  440  990 1760 2750]
Division: [0.90909091 0.90909091 0.90909091 0.90909091 0.90909091]
Power: [ 100  400  900 1600 2500]


In [45]:
data = np.array([22,45,21,36,98,26])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))

Sum: 248
Mean: 41.333333333333336
Minimum: 21
Maximum: 98
Standard deviation: 26.693736260695232
Variance: 712.5555555555555


In [51]:
nums = np.array([121, 144, 49, 256])

print("Square root:", np.sqrt(nums))
print("Exponential:", np.exp(nums))
print("Natural log:", np.log(nums))
print("Sine:", np.sin(nums))

Square root: [11. 12.  7. 16.]
Exponential: [3.54513118e+052 3.45466066e+062 1.90734657e+021 1.51142767e+111]
Natural log: [4.79579055 4.9698133  3.8918203  5.54517744]
Sine: [ 0.99881522 -0.49102159 -0.95375265 -0.99920803]


In [52]:
# Matrix operations
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Element-wise multiplication:\n", m1 * m2)
print("Matrix multiplication (dot):\n", np.dot(m1, m2))
print("Matrix multiplication (matmul):\n", np.matmul(m1, m2))

Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication (dot):
 [[19 22]
 [43 50]]
Matrix multiplication (matmul):
 [[19 22]
 [43 50]]


In [53]:
p = np.array([2, 4, 6, 8, 10])
q = np.array([1, 3, 5, 7, 9])

ex3_sum = p + q
ex3_product = p * q
print("Sum:", ex3_sum)
print("Product:", ex3_product)
print("Mean of sum:", np.mean(ex3_sum))

Sum: [ 3  7 11 15 19]
Product: [ 2 12 30 56 90]
Mean of sum: 11.0


In [54]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("Full array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Elements from index 1 to 3:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

Full array: [10 20 30 40 50 60]
First element: 10
Last element: 60
Elements from index 1 to 3: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [55]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("Matrix:\n", matrix)
print("Element at row 1, col 2:", matrix[1, 2])
print("First row:", matrix[0, :])
print("First column:", matrix[:, 0])
print("Sub-matrix (rows 0-1, cols 1-2):\n", matrix[0:2, 1:3])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 6
First row: [1 2 3]
First column: [1 4 7]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]
