In [15]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array2 = np.array([[1, 2], [2, 3]])
array3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(" 1d array is:",array1)
print("2 d array is \n",array2)
print("3 d array is :\n",array3)
print("shape of array2 is :",array2.shape)
print("Shape of array3 is :",array3.shape)
print("Datatype of array1 is :",array1.dtype)
print("Mean of Array 1 is :",np.mean(array1))
print("Max of arraay 1 is :",np.max(array1))

 1d array is: [ 1  2  3  4  5  6  7  8  9 10]
2 d array is 
 [[1 2]
 [2 3]]
3 d array is :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of array2 is : (2, 2)
Shape of array3 is : (3, 3)
Datatype of array1 is : int64
Mean of Array 1 is : 5.5
Max of arraay 1 is : 10
